config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/users/registrations',
    sessions: 'devise/users/sessions'
  }
  
  root to: 'recruits#index'
  resources :recruits do
    member do
      resources :favorites, only: [:create, :destroy]
      get :assign
    end
    collection do
      get :my_lunch
    end
  end

  resource :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  has_one_attached :icon
  belongs_to :owner,    class_name: "User", foreign_key: "owner_id"
  belongs_to :assigne, class_name: "User", foreign_key: "assigne_id", optional: true
  has_many :favorites, dependent: :destroy

  enum status:{
    wanted: 0, #募集中
    full: 1, #満員
    done: 2 #募集終了
  }

  paginates_per 4
  scope :index_all, -> {
    select(:id, :shop, :location, :content, :status, :owner_id, :assigne_id, :end_on)
    .order(created_at: :asc)
    .includes(:owner)
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  has_many :owned_recruits,    class_name: "Recruit", foreign_key: "owner_id", dependent: :destroy
  has_many :assigned_recruits, class_name: "Recruit", foreign_key: "assigne_id"
  has_many :favorites, dependent: :destroy

  def assign(user_id)
    owned_recruits.create(assigne_id: user_id)
  end
  
  def withdraw(user_id)
    owned_recruits.find_by(assigne_id: user_id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    recruits_path
  end

  def after_sign_in_path_for(resource)
    recruits_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recruit

  def create
    @favorite = current_user.favorites.create(recruit_id: params[:id])
    redirect_to request.referer
  end

  def destroy
    @favorite = current_user.favorites.find_by(recruit_id: params[:id]).destroy
    redirect_to request.referer
  end

  private

  def set_recruit
    @recruit = Recruit.find(params[:id])
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  before_action :set_recruit, only: %i[ assign edit update destroy ]
  before_action :timepass
  before_action :authenticate_user!

  def index
    @recruits = Recruit.index_all.page(params[:page])
  end

  def my_lunch
    @recruits = Recruit.where(owner_id: current_user).page(params[:page])
  end

  def assign
  end
  
  def new
    @recruit = Recruit.new
  end

  def create
    @recruit = Recruit.create(recruit_params)
    @recruit.owner_id = current_user.id
    if @recruit.save
      redirect_to @recruit
    else
      render :new
    end
  end

  def show
    @recruit = Recruit.find(params[:id])
    @favorite = current_user.favorites.find_by(recruit_id: @recruit.id)
  end

  def edit
  end

  def update
    if @recruit.update(recruit_params)
      redirect_to @recruit
    else
      render :show
    end
  end

  def destroy
    if @recruit.destroy
      redirect_to recruits_url
    else
      render :index
    end
  end

  def timepass
    time = Time.now
    recruits = Recruit.all
    recruits.each do |recruit|
      if recruit.end_on < time
        recruit.status = "done"
        recruit.save
      end
    end 
  end

  private

  def recruit_params
    params.require(:recruit).permit(:shop, :location, :content, :status, :owner_id, :assigne_id, :icon, :end_on)
  end

  def set_recruit
    @recruit = Recruit.find(params[:id])
    if @recruit.owner != current_user
      redirect_to recruits_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recruites_helper.rb
module RecruitesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user: current_user, recruit_id: recruit.id) %>
  <%= link_to favorites_path(recruit), method: :post, class: "favorite-btn favorite-create" do %>
    <div class="i far fa-heart" >
      <span></span>
      <%= recruit.favorites.length %>
    </div>
  <% end %>
<% else %>
  <%= link_to favorite_path(recruit), method: :delete, class: "favorite-btn favorite-delete" do %>
    <div class="i fas fa-heart">
      <span></span>
      <%= recruit.favorites.length %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ランチしよ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">ランチしよ！</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if user_signed_in? %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'マイランチ', my_lunch_recruits_path, class: 'nav-link hover' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ランチ募集一覧', recruits_path, class: 'nav-link hover' %>
              </li>
            </ul>
            <ul class="navbar-nav" style="margin-left: auto">
              <li class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-user-circle fa-lg"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <%= link_to 'ユーザー編集', edit_users_path, class: 'dropdown-item hover' %>
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "dropdown-item hover" %>
                </div>
              </li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <%= link_to 'サインアップ', new_user_registration_path, class: 'nav-link hover' %>
              </li>
              <li class="nav-item">
                <%= link_to 'サインイン', new_user_session_path, class: 'nav-link hover' %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container" style="width: 80vw; height: 80vh">
      <div class="my-auto mt-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/recruits/_form.html.erb
<%= form_with(model: recruit) do |form| %>
  <% if recruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruit.errors.count, "error") %> prohibited this recruit from being saved:</h2>

      <ul>
        <% recruit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :店名 %><br />
    <%= form.text_field :shop %>
  </div>

  <div class="field">
    <%= form.label :場所 %><br />
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :一言 %><br />
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :期日 %><br />
    <%= form.datetime_select :end_on %>
  </div>

  <div class="field">
    <%= form.label :ステータス %><br />
    <%= form.radio_button :status, :wanted %><%= form.label :募集中 %>
    <%= form.radio_button :status, :full %><%= form.label :満員 %>
    <%= form.radio_button :status, :done %><%= form.label :募集終了 %>
  </div>

  <div class="field">
    <%= form.label :画像 %><br />
    <%= image_tag(recruit.icon.variant(gravity: :center, resize:"100x100^", crop:"1000x100+0+0").processed) if recruit.icon.attached? %><br />
    <%= form.file_field :icon %>
  </div>
  
  <br />
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recruits/_index_card.html.erb
<div class="row g-0">
  <div class="col-md-8">
    <div class="card-body">
      <p class="card-name">募集者：<%= recruit.owner.name %><p>
      <p class="card-text">ご指名：<%= recruit.assigne.nil? ? "なし" : recruit.assigne.name%></p>
      <p class="card-text">期日：<%= recruit.end_on.strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
      <p class="card-text">ステータス：<%= recruit.status_i18n %></p>
      <div class="recruit-links">
        <%= link_to '詳細', recruit_path(recruit), class: 'btn btn-outline-secondary' %>
        <% if recruit.owner_id == current_user.id %>
          <%= link_to '編集', edit_recruit_path(recruit), class: 'btn btn-outline-success' %>
          <%= link_to '削除', recruit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4 image_box">
    <%= image_tag(recruit.icon.variant(gravity: :center, resize:"130x130^", crop:"130x130+0+0").processed, style: "margin: auto;") if recruit.icon.attached? %>
  </div>
</div>

app/views/recruits/_list.html.erb
<div id="new-recruit-link">
  <%= link_to '新規ランチ募集', new_recruit_path, class: 'hover btn btn-light' %>
</div>

<div class="row justify-content-evenly card_box">
  <% recruits.each do |recruit| %>
    <% if recruit.owner_id == current_user.id %>
      <div class="card border-success mt-lg-3 mt-sm-5 col-sm-12 col-lg-5" style="padding: 0">
        <div id="#favorite_<%= recruit.id %>", class="card-header bg-success bg-gradient bg-opacity-25 fw-bolder fs-4 flexcard">
          <%= recruit.shop %>
          <%= render 'favorites/favorite', recruit: recruit %>
        </div>
        <%= render 'index_card', recruit: recruit %>
      </div>
    <% elsif %>
      <div class="card border-danger mt-lg-3 mt-sm-5 col-sm-12 col-lg-5" style="padding: 0">
        <div id="#favorite_<%= recruit.id %>", class="card-header bg-danger bg-gradient bg-opacity-25 fw-bolder fs-4 flexcard">
          <%= recruit.shop %>
          <%= render 'favorites/favorite', recruit: recruit %>
        </div>
        <%= render 'index_card', recruit: recruit %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="pagenate">
  <%= paginate recruits %>
</div>

app/views/recruits/_show_card.html.erb
<div class="row g-0">
  <div class="col-md-8">
    <div class="card-body">
      <p class="card-name">募集者：<%= recruit.owner.name %></h5>
      <p class="card-text">ご指名：<%= recruit.assigne.nil? ? "なし" : recruit.assigne.name%></p>
      <p class="card-text">場所：<%= recruit.location %></p>
      <p class="card-text">一言：<%= recruit.content %></p>
      <p class="card-text">期日：<%= recruit.end_on.strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
      <p class="card-text">ステータス：<%= recruit.status_i18n %></p>
      <div class="recruit-links">
        <%= link_to '一覧へ戻る', recruits_path, class: 'btn btn-outline-secondary' %>
        <% if recruit.owner_id == current_user.id %>
          <%= link_to '編集', edit_recruit_path(recruit), class: 'btn btn-outline-success' %>
          <%= link_to 'アサイン',  assign_recruit_path(recruit), class: 'btn btn-outline-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4 image_box">
    <%= image_tag(recruit.icon.variant(gravity: :center, resize:"130x130^", crop:"130x130+0+0").processed, style: "margin: auto;") if recruit.icon.attached? %>
  </div>
</div>

app/views/recruits/assign.html.erb
<h2>ランチ募集のご指名</h2>
<div class="row justify-content-evenly">
  <div class="col-sm-12 col-lg-6">
    <%= form_with(model: @recruit) do |form| %>
      <% if @recruit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@recruit.errors.count, "error") %> prohibited this recruit from being saved:</h2>

          <ul>
            <% @recruit.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <p>現在のご指名</p>
        <%= @recruit.assigne.nil? ? "なし" : @recruit.assigne.name%>
      </div>
      <br />

      <div class="field">
        <p>ご指名の変更</p>
        <%= form.collection_select :assigne_id, User.all, :id, :name , include_blank: "-- 選択して下さい --" , class: 'col-md-9' %>
      </div>
      
      <br />
      <div class="actions">
        <%= form.submit :ご指名する, class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="card border-success mt-4 col-sm-12 col-lg-6" style="padding: 0">
    <div class="card-header bg-success bg-gradient bg-opacity-25 fw-bolder fs-4"><%= @recruit.shop %></div>
    <%= render 'show_card', recruit: @recruit %>
  </div>
</div>

app/views/recruits/edit.html.erb
<div class="my-auto mt-5">
  <h1>ランチ募集の編集</h1>
</div>

<%= render 'form', recruit: @recruit %>
<br />

<%= link_to '詳細', @recruit, class: 'btn btn-outline-secondary' %> |
<%= link_to '一覧へ戻る', recruits_path, class: 'btn btn-outline-success' %>

app/views/recruits/index.html.erb
<h2>ランチ募集一覧</h2>
<%= render 'list', recruits: @recruits %>

app/views/recruits/my_lunch.html.erb
<h2>マイランチ</h2>
<%= render 'list', recruits: @recruits %>

app/views/recruits/new.html.erb
<h2>新規ランチ募集の作成</h2>

<%= render 'form',  recruit: @recruit %>
<br />
<%= link_to '一覧へ戻る', recruits_path, class: 'btn btn-outline-success' %>

app/views/recruits/show.html.erb
<h2>ランチ募集詳細</h2>
<div class="row justify-content-center">
  <% if @recruit.owner_id == current_user.id %>
    <div class="card border-success mt-5 col-sm-12 col-lg-8" style="padding: 0">
      <div id="#favorite_<%= @recruit.id %>", class="card-header bg-success bg-gradient bg-opacity-25 fw-bolder fs-4 flexcard">
        <%= @recruit.shop %>
        <%= render 'favorites/favorite', recruit: @recruit %>
      </div>
      <%= render 'show_card', recruit: @recruit %>
    </div>
  <% elsif %>
    <div class="card border-danger mt-5 col-sm-12 col-lg-8" style="padding: 0">
      <div id="#favorite_<%= @recruit.id %>", class="card-header bg-danger bg-gradient bg-opacity-25 fw-bolder fs-4 flexcard">
        <%= @recruit.shop %>
        <%= render 'favorites/favorite', recruit: @recruit %>
      </div>
      <%= render 'show_card', recruit: @recruit %>
    </div>
  <% end %>
</div>